spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/trawell
    username: trawell
    password: .Hippi62
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
logging:
  level:
    org:
      hibernate:
        type: trace