spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      database: trawell
      host: localhost
      port: 27017
aut:
  app:
    jwtExpirationMs: 76300000
    jwtSecret: knowledgeFactory
logging:
  level:
    org:
      hibernate:
        type: trace
