spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      spring:
        servlet:
          multipart:
            enabled: true
            max-file-size: 42768929MB
            max-request-size: 42768929MB
        http:
          multipart:
            enabled: true
            max-file-size: 42768929MB
            max-request-size: 42768929MB
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      database: trawell
      host: localhost
      #host: host.docker.internal
      port: 27017
aut:
  app:
    jwtExpirationMs: 76300000
    jwtSecret: knowledgeFactory
logging:
  level:
    org:
      hibernate:
        type: trace
